### ISSUE TITLE
mamaproducerc_v2 SEGV's on shutdown

### ISSUE THREAD

**Issue by btorpey** [finos/OpenMAMA#267]
# mamaproducerc_v2 SEGV's on shutdown
## Summary
mamaproducerc_v2 SEGV's on shutdown

## Areas Affected
- [x] MAMAC
- [ ] MAMACPP
- [ ] MAMADOTNET
- [ ] MAMAJNI
- [ ] MAMDA
- [ ] MAMDACPP
- [ ] MAMDADOTNET
- [ ] MAMDAJNI
- [ ] Visual Studio
- [ ] SCons
- [ ] Unit Tests
- [x] Examples

## Details
This appears to happen every time.

Command line used (see https://github.com/OpenMAMA/OpenMAMA/issues/265):

    mamaproducerc_v2 -numTopics 10000 -rt -tport pub -m qpid -target 100000 -steps 5,10,15,20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100 -stepInterval 10

and for consumer:

    mamaconsumerc_v2 -tport sub -m qpid -genSyms 10000 -csv report2.csv

It's also consistent between 6.2.0 rpm install or build from source, with qpid libs in standard location (/usr/lib64) and built from source.

[gdb-14895.txt](https://github.com/OpenMAMA/OpenMAMA/files/937797/gdb-14895.txt)
[gdb-13768.txt](https://github.com/OpenMAMA/OpenMAMA/files/937798/gdb-13768.txt)

**Comment by fquinner** [comment]
Yeah I can recreate this though only if the consumer is still connected when the producer stops. If i stop the consumer first, it exits fine.

**Comment by bill-torpey** [comment]
This appears to be a consistent issue with qpid bridge.  It looks like a memory overwrite problem -- note that displaying `wtable` as a `char*` gives a valid string:

![Screenshot from 2020-08-27 13-51-11](https://user-images.githubusercontent.com/11855062/91567077-8b103600-e912-11ea-9736-327456853990.png)

**Comment by fquinner** [comment]
Ha that's amazing have you tried this including the configuration option to leave the payload bridge open? Because I vaguely remember having suspicions that was related to this one but maybe it wasn't.

**Comment by bill-torpey** [comment]
The crash happens in `mamaTransport_destroy`, so `mama_close` hasn't been called yet.

valgrind is not very helpful either ...

```
==18:08:30.397484 10166== Invalid read of size 8
==18:08:30.397532 10166==    at 0x613ECC3: wtable_for_each (wtable.c:60)
==18:08:30.397541 10166==    by 0x507AE70: endpointPoolImpl_destroySubTable (endpointpool.c:620)
==18:08:30.397546 10166==    by 0x613ECF4: wtable_for_each (wtable.c:64)
==18:08:30.397550 10166==    by 0x507AE70: endpointPoolImpl_destroySubTable (endpointpool.c:620)
==18:08:30.397554 10166==    by 0x613ECF4: wtable_for_each (wtable.c:64)
==18:08:30.397570 10166==    by 0x507A69E: endpointPool_destroyWithCallback (endpointpool.c:210)
==18:08:30.397576 10166==    by 0x71EEB07: qpidBridgeMamaTransport_destroy (transport.c:297)
==18:08:30.397582 10166==    by 0x50BF9BB: mamaTransport_destroy (transport.c:1291)
==18:08:30.397604 10166==    by 0x4E43039: oz::connection::destroy() (ozimpl.cpp:33)
==18:08:30.397630 10166==    by 0x40448C: oz::{lambda(oz::connection*)#7}::operator()(oz::connection*) const (ozimpl.h:401)
==18:08:30.397641 10166==    by 0x404CB2: std::unique_ptr<oz::connection, oz::{lambda(oz::connection*)#7}>::~unique_ptr() (unique_ptr.h:184)
==18:08:30.397645 10166==    by 0x4049E5: main (pub.cpp:25)
==18:08:30.397649 10166==  Address 0x312e302e302e3732 is not stack'd, malloc'd or (recently) free'd
```

**Comment by fquinner** [comment]
Ah lovely, will have a proper look at this again next week

**Comment by bill-torpey** [comment]
One more thing -- the crash seems to only happen if at least one subscriber has connected.

**Comment by fquinner** [comment]
https://github.com/finos/OpenMAMA/pull/497
