### ISSUE TITLE
unit tests fail if optional I/O component not implemented

### ISSUE THREAD

**Issue by bill-torpey** [finos/OpenMAMA#458]
# unit tests fail if optional I/O component not implemented
## Summary
The [Bridge Documentation](https://openmama.finos.org/openmama_bridge.html) page states that the I/O component is optional, and describes how to accomplish that:

> If the underlying middleware does not support the registration of IO events, then the above method returns MAMA_STATUS_UNSUPPORTED_IO_TYPE or MAMA_STATUS_NOT_IMPLEMENTED.

However, the unit tests don't take that into account, and fail when run against a transport bridge that does not implement the I/O component:

```
...
[----------] 2 tests from MamaIoTestC
[ RUN      ] MamaIoTestC.CreateDestroy
/home/btorpey/work/OpenMAMA/master/src/mama/c_cpp/src/gunittest/c/iotest.cpp:93: Failure
      Expected: MAMA_STATUS_OK
      Which is: 0
To be equal to: mamaIo_create (&io, queue, descriptor, onIo, ioType, m_this)
      Which is: 16
[  FAILED  ] MamaIoTestC.CreateDestroy (3 ms)
[ RUN      ] MamaIoTestC.getDescriptor
/home/btorpey/work/OpenMAMA/master/src/mama/c_cpp/src/gunittest/c/iotest.cpp:118: Failure
      Expected: MAMA_STATUS_OK
      Which is: 0
To be equal to: mamaIo_create (&io, queue, descriptor, onIo, ioType, m_this)
      Which is: 16
[  FAILED  ] MamaIoTestC.getDescriptor (3 ms)
[----------] 2 tests from MamaIoTestC (6 ms total)
...
[----------] Global test environment tear-down
[==========] 201 tests from 18 test cases ran. (12921 ms total)
[  PASSED  ] 199 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] MamaIoTestC.CreateDestroy
[  FAILED  ] MamaIoTestC.getDescriptor

 2 FAILED TESTS
  YOU HAVE 2 DISABLED TESTS
```

Since the I/O component is documented as optional, it seems that the test suite should be smart enough to detect that the component is unimplemented and return MAMA_STATUS_OK in this case.

I'm happy to prepare a PR to implement this behavior if you agree that it is correct.

**Comment by fquinner** [comment]
Yeah it looks like it's missing some `CHECK_NON_IMPLEMENTED_OPTIONAL` calls in there. A PR would be much appreciated thanks!
